### ISSUE TITLE
The dynamic island UI not showing

### ISSUE THREAD

**Issue by anitakr** [blorenzo10/coffee-shop-demo#2]
Hi

I am having trouble getting this to work. I simply cloned the project and build it on a iPhone 15 simulator. 
The dynamic island works as expected except that there is no UI visible. 

Any tips?

macOS: 13.5
Xcode: 15.2

**Comment by blorenzo10** [comment]
Ho @anitakr, what do you mean by "no UI visible"? Could you upload a quick video? 

It's working for me 👇 

https://github.com/blorenzo10/coffee-shop-demo/assets/20937316/8fa5734d-7f85-4863-8ba1-382805dfda28

I'm running macOS 14 and Xcode 15.0

**Comment by anitakr** [comment]
Hi and thank you for replying. 
I tried updating my macOS to your version and then it worked 👏
